### ISSUE TITLE
No entities returned

### ISSUE THREAD

**Issue by slidenerd** [26medias/node-ner#3]
First of all, thank you for your fantastic effort. It has made life a lot simpler for NLP guys. I have a file.txt with this input
What is the weather at mumbai
what is the weather in coimbatore
what is the temperature at bangalore
how is the forecast at Hong Kong

The entities returns {} when I run it. I also noticed however that if I put a considerable amount of information, then it returns entities, does that mean i simply need a much bigger data set? I am interested in performing NER on a sentence by sentence basis rather than a corpus. What do you feel would be the right way to go about it without using api.ai/wit.ai and their cousins?

Thank you for your answers in advance

**Comment by jconde** [comment]
Hi @slidenerd , node-ner is just a nodejs wrapper around NER that creates a JSON out of the Java standard output. This issue should be off-topic unless the Java Stanford NER is tagging those words in its output as locations and the node-ner output is not reflecting it.

Also, as a tip while using NER, I would try:
1. Writing the locations when possible with capital case (e.g. `Mumbai` instead of `mumbai`), and
2. Playing with the other NER classifiers.

I've noticed NER is very sensitive to what's on point 1. This is the output I get after changing the locations to capital case and switching to the `english.all.3class.distsim.crf.ser.gz` classifier:

`{"LOCATION":["Mumbai","Coimbatore","Bangalore","Hong Kong"]}`
